sources = main.c drugi.h funk1.c funk2.c funk3.c globalne.h pierwszy.h trzeci.h

programs = $(basename $(sources))
objects = $(addsuffix .o, $(programs))

CFLAGS = -Wall -std=c11
LDLIBS = -lm

.PHONY : clean
clean :
	-$(RM) $(objects) $(programs) *~

all : $(programs)
